### ISSUE TITLE
Operator "enum&.value" require ruby 2.3.0

### ISSUE THREAD

**Issue by toshidavila** [dblock/ruby-enum#23]
Hi,

this operator requires ruby 2.3.0

https://github.com/dblock/ruby-enum/blob/c6a2e67b64277e9a822630174c691dbfe9181ecf/lib/ruby-enum/enum.rb#L90

Using ruby 2.1.7 fails with an "unexpected error"

```
/home/.rvm/gems/ruby-2.1.7/gems/ruby-enum-0.8.0/lib/ruby-enum.rb:6:in 'require': /home/.rvm/gems/ruby-2.1.7/gems/ruby-enum-0.8.0/lib/ruby-enum/enum.rb:90: syntax error, unexpected '.' (SyntaxError)
        enum&.value
              ^
/home/.rvm/gems/ruby-2.1.7/gems/ruby-enum-0.8.0/lib/ruby-enum/enum.rb:111: syntax error, unexpected '.'
        enum&.key
              ^
              from /home/.rvm/gems/ruby-2.1.7/gems/ruby-enum-0.8.0/lib/ruby-enum.rb:6:in '<top (required)>'```

**Comment by dblock** [comment]
Ruby 2.3.x is EOL, https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/. Use an older version please.
